// AI Flow Classifier 1.0.0
// Copyright 2026 Summon Software Labs.
// SPDX-License-Identifier: Apache-2.0
//
// Property tests for contradiction reporting.
//
// REAL / SYNTHETIC
// ----------------
// The evidence sets are SYNTHETIC, generated by the seeded generator below.  The rules
// checked are REAL: they are asserted against the aifc::Classification that
// aifc::DecisionEngine::decide() returns, using only the public header.
//
// Vocabulary, and one honest discrepancy
// --------------------------------------
// This file uses "current authoritative record" to mean exactly what the decision engine
// means by it in its contradiction filter (src/classify/decision_engine.cpp, step 4): the
// record is CURRENT after the engine's own currentness pass, and its source is not
// HEURISTIC.  Two narrower descriptions exist in the tree and neither is the rule the code
// implements:
//
//   * aifc::source_is_authoritative() is rank >= CONTRACT_DERIVED, so it excludes
//     COORDINATOR_CORRELATED and TOPOLOGY_CORRELATED; the engine's filter does not;
//   * the header comment of decision_engine.hpp says "two CURRENT records with the same
//     rank that disagree are a contradiction"; the engine reports a disagreement between
//     current non-heuristic records at *different* ranks as well.
//
// The generated sets therefore include records at every non-heuristic rank, and the
// property asserted is the engine's actual rule: a contradiction is listed if and only if
// at least two CURRENT non-heuristic records declare different classes.
//
// Precondition on the threshold
// -----------------------------
// The randomized cases configure minimum_publishable_confidence = 1.  Under that policy a
// penalised decision is always publishable, so the below-threshold path (which clears the
// contradiction list, because an unpublishable decision reports no penalty) cannot mask a
// contradiction.  That path is exercised deliberately by
// "contradiction.below_threshold_suppresses_the_penalty_but_not_the_disagreement".
//
// Reproduction
// ------------
//     set AIFC_TEST_SEED=0x0123456789abcdef
//     build\tests-b\bin\test_contradiction_properties.exe
// Every failure message carries the seed it used and the same replay instruction.

#include <cstdint>
#include <cstdlib>
#include <map>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

#include "synthetic.hpp"
#include "test_framework.hpp"

namespace {

// ---------------------------------------------------------------------------
// Seeded case driver
// ---------------------------------------------------------------------------

[[nodiscard]] std::uint64_t parse_seed_text(const std::string& text) {
  try {
    std::size_t consumed = 0;
    const std::uint64_t value = std::stoull(text, &consumed, 0);
    if (consumed == text.size()) return value;
  } catch (const std::exception&) {
    // Not a number: fall through to the deterministic text hash below.
  }
  return aifc::seed_from_text(text);
}

class SeededCase {
 public:
  explicit SeededCase(std::string name)
      : name_(std::move(name)), seed_(resolve_seed(name_)), rng_(seed_) {}

  [[nodiscard]] aifc::Rng& rng() noexcept { return rng_; }
  [[nodiscard]] std::uint64_t seed() const noexcept { return seed_; }

  [[nodiscard]] std::string where(std::uint32_t step, const std::string& detail) const {
    std::ostringstream out;
    out << "case=" << name_ << " " << aifc::format_seed(seed_) << " step=" << step;
    if (!detail.empty()) out << " -- " << detail;
    out << " [replay: set AIFC_TEST_SEED=" << seed_ << "]";
    return out.str();
  }

  void check(bool condition, std::uint32_t step, const std::string& detail) {
    if (!condition) AIFC_FAIL(where(step, detail));
  }

 private:
  [[nodiscard]] static std::uint64_t resolve_seed(const std::string& name) {
    const char* override_text = std::getenv("AIFC_TEST_SEED");
    if (override_text != nullptr && *override_text != '\0') return parse_seed_text(override_text);
    return aifc::seed_from_text(name);
  }

  std::string name_;
  std::uint64_t seed_ = 0;
  aifc::Rng rng_;
};

[[nodiscard]] std::size_t failure_count() {
  return aifc_test::Registry::instance().failures().size();
}

// ---------------------------------------------------------------------------
// Value rendering
// ---------------------------------------------------------------------------

[[nodiscard]] std::string describe(const aifc::EvidenceRecord& record) {
  std::ostringstream out;
  out << "id=" << record.id.value() << " source=" << aifc::to_string(record.source) << "(rank "
      << static_cast<unsigned>(aifc::source_rank(record.source))
      << ") class=" << aifc::to_string(record.semantic) << " state=" << aifc::to_string(record.state)
      << " workload_generation=" << record.workload_generation.value
      << " evidence_generation=" << record.generation.value
      << " accepted_seq=" << record.accepted_seq << " publisher=" << record.publisher.value() << "@"
      << record.publisher_boot.to_string() << " accepted_epoch=" << record.accepted_epoch.to_string()
      << " flow_generation=" << record.flow_generation.to_string();
  return out.str();
}

[[nodiscard]] std::string describe(const aifc::EvidenceCitation& citation) {
  std::ostringstream out;
  out << "id=" << citation.id.value() << " source=" << aifc::to_string(citation.source)
      << " state=" << aifc::to_string(citation.state)
      << " class=" << aifc::to_string(citation.semantic)
      << " disposition=" << aifc::to_string(citation.disposition)
      << " confidence=" << citation.confidence.to_decimal();
  return out.str();
}

[[nodiscard]] std::string describe(const aifc::Classification& classification) {
  std::ostringstream out;
  out << "semantic=" << aifc::to_string(classification.semantic)
      << " state=" << aifc::to_string(classification.state)
      << " confidence=" << classification.confidence.to_decimal() << " selected="
      << (classification.selected_evidence.empty() ? std::string("<none>")
                                                   : classification.selected_evidence.value())
      << " selected_source=" << aifc::to_string(classification.selected_source)
      << " corroboration=" << classification.corroboration_count
      << " penalty=" << classification.applied_penalty_basis_points
      << " contradictions=" << classification.contradictions.size()
      << " digest=" << classification.digest.to_hex();
  return out.str();
}

[[nodiscard]] std::string describe(const aifc::ClassificationContradiction& contradiction) {
  std::ostringstream out;
  out << "left=" << contradiction.left_id.value() << "("
      << aifc::to_string(contradiction.left_class) << "/"
      << aifc::to_string(contradiction.left_source) << ")"
      << " right=" << contradiction.right_id.value() << "("
      << aifc::to_string(contradiction.right_class) << "/"
      << aifc::to_string(contradiction.right_source) << ")"
      << " resolved_by=\"" << contradiction.resolved_by << "\"";
  return out.str();
}

[[nodiscard]] std::string describe_list(const std::vector<aifc::ClassificationContradiction>& list) {
  std::ostringstream out;
  out << "[";
  for (std::size_t i = 0; i < list.size(); ++i) {
    if (i != 0) out << ", ";
    out << "{" << describe(list[i]) << "}";
  }
  out << "]";
  return out.str();
}

// ---------------------------------------------------------------------------
// Seeded value generation
// ---------------------------------------------------------------------------

const aifc::SemanticClass kPalette[3] = {
    aifc::SemanticClass::COLLECTIVE,
    aifc::SemanticClass::INFERENCE_REQUEST,
    aifc::SemanticClass::KV_STATE_TRANSFER,
};

// Every non-heuristic source rank, plus HEURISTIC, so that a disagreement at any rank is
// generated and the heuristic case is generated alongside it.
const aifc::EvidenceSource kSources[aifc::kEvidenceSourceCount - 1U] = {
    aifc::EvidenceSource::HEURISTIC,
    aifc::EvidenceSource::TOPOLOGY_CORRELATED,
    aifc::EvidenceSource::COORDINATOR_CORRELATED,
    aifc::EvidenceSource::CONTRACT_DERIVED,
    aifc::EvidenceSource::DECLARED_AUTHENTICATED,
};

const aifc::EvidenceState kDecoyStates[4] = {
    aifc::EvidenceState::EVIDENCE_STALE,
    aifc::EvidenceState::EVIDENCE_SUPERSEDED,
    aifc::EvidenceState::EVIDENCE_REVOKED,
    aifc::EvidenceState::EVIDENCE_INSUFFICIENT,
};

[[nodiscard]] std::uint64_t pick_u64(aifc::Rng& rng, const std::uint64_t* values,
                                     std::size_t count) {
  return values[static_cast<std::size_t>(rng.next_below(count))];
}

[[nodiscard]] aifc::AuthorityContext make_authority() {
  aifc::AuthorityContext authority;
  authority.epoch = aifc::CoordinatorEpoch{1};
  authority.coordinator_boot = aifc::CoordinatorBootId{1};
  authority.tick = aifc::kTickNone;
  for (std::uint32_t index = 0; index < 5U; ++index) {
    const aifc::PublisherId publisher = aifc_test::synthetic_publisher(index);
    authority.known_publishers.insert(publisher.value());
    authority.live_publisher_boots.insert(
        aifc::AuthorityContext::boot_key(publisher, aifc::PublisherBootId{1}));
  }
  return authority;
}

struct GeneratedSet {
  aifc::FlowRecord flow;
  std::vector<aifc::EvidenceRecord> records;
  aifc::DecisionInput input;
};

[[nodiscard]] GeneratedSet generate_set(SeededCase& seeded, std::uint32_t step,
                                        aifc::ClassifierPolicy& policy) {
  aifc::Rng& rng = seeded.rng();
  GeneratedSet set;
  set.flow.key = aifc_test::synthetic_flow_key(step);
  set.flow.id = aifc::derive_flow_id(set.flow.key);
  set.flow.generation = aifc::FlowGeneration{1};
  set.flow.registered_by = aifc_test::synthetic_session(0);

  const aifc::AuthorityContext authority = make_authority();

  const std::uint64_t penalties[4] = {0U, 500U, 2000U, 4000U};
  policy = aifc::ClassifierPolicy::initial();
  policy.allow_heuristic_evidence = rng.next_bool();
  policy.contradiction_penalty = static_cast<std::uint32_t>(pick_u64(rng, penalties, 4U));
  // Documented precondition: a penalised decision must stay publishable, so that the
  // below-threshold path cannot mask a contradiction.  The lowest source confidence among
  // the sources that can win is 5000 (TOPOLOGY_CORRELATED), and the largest penalty here
  // is 4000, so the penalised confidence is never below 1000.
  policy.minimum_publishable_confidence = 1U;

  const std::uint32_t count = 3U + static_cast<std::uint32_t>(rng.next_below(7U));  // 3..9
  set.records.reserve(count);
  for (std::uint32_t index = 0; index < count; ++index) {
    aifc::EvidenceRecord record;
    record.id = aifc::make_evidence_id("ev-" + std::to_string(2000U + index));
    record.publisher = aifc_test::synthetic_publisher(index % 5U);
    record.publisher_boot = aifc::PublisherBootId{1};
    record.session = aifc_test::synthetic_session(index % 5U);
    record.accepted_boot = authority.coordinator_boot;
    record.accepted_epoch = authority.epoch;
    record.workload = aifc_test::synthetic_workload(index % 3U);
    record.workload_generation = aifc::WorkloadGeneration{1U + rng.next_below(3U)};
    record.flow_id = set.flow.id;
    record.flow_generation = set.flow.generation;
    record.generation = aifc::EvidenceGeneration{1U + rng.next_below(3U)};
    record.accepted_seq = 1U + rng.next_below(8U);
    record.accepted_tick = 10U + rng.next_below(5U);
    record.fresh_until = 500U;
    record.semantic = kPalette[static_cast<std::size_t>(rng.next_below(3U))];
    record.source = kSources[static_cast<std::size_t>(rng.next_below(aifc::kEvidenceSourceCount - 1U))];
    record.state = aifc::EvidenceState::EVIDENCE_CURRENT;
    record.confidence = aifc::source_confidence(record.source);
    record.metadata.topic = "topic-" + std::to_string(index);
    record.metadata.reason = "synthetic contradiction evidence";

    // Decoys: a record that is not current must never contradict, whatever it declares.
    if (rng.next_below(100U) < 15U) {
      // A class that no other record declares makes the decoy maximally disruptive if it
      // were wrongly treated as current.
      record.semantic = aifc::SemanticClass::MODEL_STATE_TRANSFER;
      switch (rng.next_below(4U)) {
        case 0U:
          record.state = kDecoyStates[0];
          break;
        case 1U:
          record.state = kDecoyStates[1];
          break;
        case 2U:
          record.state = kDecoyStates[2];
          break;
        default:
          record.state = kDecoyStates[3];
          break;
      }
    } else if (rng.next_below(100U) < 10U) {
      // Exactly the same shape of record, bound to another flow generation: not current.
      record.flow_generation = aifc::FlowGeneration{set.flow.generation.value + 1U};
      record.semantic = aifc::SemanticClass::MODEL_STATE_TRANSFER;
    } else if (rng.next_below(100U) < 10U) {
      // Accepted in another coordinator epoch: not current.
      record.accepted_epoch = aifc::CoordinatorEpoch{authority.epoch.value + 1U};
      record.semantic = aifc::SemanticClass::MODEL_STATE_TRANSFER;
    }

    record.content_digest = aifc::compute_evidence_digest(record);
    set.records.push_back(record);
  }

  set.input.flow = set.flow;
  set.input.evidence = set.records;
  set.input.policy = policy;
  set.input.authority = authority;
  set.input.generation_revoked = false;
  return set;
}

// ---------------------------------------------------------------------------
// The engine's own classification of each citation
// ---------------------------------------------------------------------------

// CURRENT and not heuristic: the engine's contradiction filter.
[[nodiscard]] bool citation_is_authoritative_current(const aifc::EvidenceCitation& citation) {
  return citation.state == aifc::EvidenceState::EVIDENCE_CURRENT &&
         !aifc::source_is_heuristic(citation.source);
}

[[nodiscard]] bool citation_is_eligible(const aifc::EvidenceCitation& citation) {
  return citation_is_authoritative_current(citation) && !aifc::is_unknown(citation.semantic);
}

[[nodiscard]] std::map<std::string, const aifc::EvidenceRecord*> index_by_id(
    const std::vector<aifc::EvidenceRecord>& records) {
  std::map<std::string, const aifc::EvidenceRecord*> by_id;
  for (const aifc::EvidenceRecord& record : records) by_id[record.id.value()] = &record;
  return by_id;
}

[[nodiscard]] const aifc::EvidenceRecord* eligible_maximum(
    const aifc::Classification& classification,
    const std::map<std::string, const aifc::EvidenceRecord*>& by_id) {
  const aifc::EvidenceRecord* best = nullptr;
  for (const aifc::EvidenceCitation& citation : classification.citations) {
    if (!citation_is_eligible(citation)) continue;
    const auto found = by_id.find(citation.id.value());
    if (found == by_id.end()) continue;
    const aifc::EvidenceRecord* candidate = found->second;
    if (best == nullptr || aifc::evidence_outranks(*candidate, *best)) best = candidate;
  }
  return best;
}

[[nodiscard]] const aifc::EvidenceCitation* find_citation(
    const aifc::Classification& classification, const aifc::EvidenceId& id) {
  for (const aifc::EvidenceCitation& citation : classification.citations) {
    if (citation.id == id) return &citation;
  }
  return nullptr;
}

[[nodiscard]] bool same_contradictions(const std::vector<aifc::ClassificationContradiction>& left,
                                      const std::vector<aifc::ClassificationContradiction>& right) {
  if (left.size() != right.size()) return false;
  for (std::size_t i = 0; i < left.size(); ++i) {
    if (left[i].left_id != right[i].left_id || left[i].right_id != right[i].right_id) return false;
    if (left[i].left_class != right[i].left_class || left[i].right_class != right[i].right_class) {
      return false;
    }
    if (left[i].left_source != right[i].left_source ||
        left[i].right_source != right[i].right_source) {
      return false;
    }
    if (left[i].resolved_by != right[i].resolved_by) return false;
  }
  return true;
}

void shuffle(std::vector<aifc::EvidenceRecord>& records, aifc::Rng& rng) {
  if (records.size() < 2) return;
  for (std::size_t i = records.size() - 1; i > 0; --i) {
    const std::size_t j = static_cast<std::size_t>(rng.next_below(i + 1U));
    const aifc::EvidenceRecord swap = records[i];
    records[i] = records[j];
    records[j] = swap;
  }
}

// ---------------------------------------------------------------------------
// The property
// ---------------------------------------------------------------------------

void contradiction_step(SeededCase& seeded, std::uint32_t step) {
  const std::size_t before = failure_count();

  aifc::ClassifierPolicy policy;
  const GeneratedSet set = generate_set(seeded, step, policy);
  const std::map<std::string, const aifc::EvidenceRecord*> by_id = index_by_id(set.records);

  aifc::DecisionEngine engine;
  const aifc::Classification classification = engine.decide(set.input);

  // (1) A contradiction is reported if and only if two or more CURRENT authoritative
  // records disagree on the class.
  const aifc::EvidenceRecord* winner = eligible_maximum(classification, by_id);
  std::vector<const aifc::EvidenceCitation*> authoritative;
  for (const aifc::EvidenceCitation& citation : classification.citations) {
    if (!citation_is_authoritative_current(citation)) continue;
    if (aifc::is_unknown(citation.semantic)) continue;
    authoritative.push_back(&citation);
  }
  std::vector<const aifc::EvidenceCitation*> disagreeing;
  if (winner != nullptr) {
    for (const aifc::EvidenceCitation* citation : authoritative) {
      if (citation->semantic != winner->semantic) disagreeing.push_back(citation);
    }
  }

  seeded.check(classification.citations.size() == set.records.size(), step,
               "citation count " + std::to_string(classification.citations.size()) +
                   " does not cover every considered record (" +
                   std::to_string(set.records.size()) + "): " + describe(classification));
  if (failure_count() != before) return;

  if (winner != nullptr) {
    seeded.check(classification.selected_evidence == winner->id, step,
                 "the winner is not the maximum eligible record (expected {" + describe(*winner) +
                     "}): " + describe(classification));
    seeded.check(classification.semantic == winner->semantic, step,
                 "the reported class is not the winner's class: " + describe(classification));
    if (failure_count() != before) return;
  } else {
    seeded.check(classification.selected_evidence.empty() &&
                     aifc::is_unknown(classification.semantic),
                 step, "no eligible record exists yet a class was reported: " +
                           describe(classification));
    if (failure_count() != before) return;
  }

  if (!disagreeing.empty()) {
    if (classification.contradictions.empty()) {
      seeded.check(false, step,
                   "two or more CURRENT authoritative records disagree (winner " +
                       describe(*winner) + ", " + std::to_string(disagreeing.size()) +
                       " disagreeing) but no contradiction was reported: " +
                       describe(classification));
      return;
    }
  } else if (!classification.contradictions.empty()) {
    seeded.check(false, step,
                 "a contradiction was reported although no two CURRENT authoritative records "
                 "disagree: " + describe(classification) + " list=" +
                     describe_list(classification.contradictions));
    return;
  }

  // (2) The list is exactly one entry per disagreeing current authoritative record, always
  // naming the winner as the left side, and never a pair that agrees.
  if (classification.contradictions.size() != disagreeing.size()) {
    seeded.check(false, step,
                 "contradiction count " + std::to_string(classification.contradictions.size()) +
                     " does not equal the " + std::to_string(disagreeing.size()) +
                     " disagreeing current authoritative records: " + describe(classification) +
                     " list=" + describe_list(classification.contradictions));
    return;
  }
  for (const aifc::ClassificationContradiction& contradiction : classification.contradictions) {
    if (contradiction.left_id != winner->id) {
      seeded.check(false, step, "the left side of " + describe(contradiction) +
                                    " is not the winner " + winner->id.value() + ": " +
                                    describe(classification));
      return;
    }
    if (contradiction.left_class != winner->semantic) {
      seeded.check(false, step, "the left class of " + describe(contradiction) +
                                    " is not the winner's class: " + describe(classification));
      return;
    }
    if (contradiction.left_class == contradiction.right_class) {
      seeded.check(false, step,
                   "a contradiction was reported between two records that agree on the class: " +
                       describe(contradiction));
      return;
    }
    if (contradiction.resolved_by.empty()) {
      seeded.check(false, step, "a contradiction carries no resolution text: " +
                                    describe(contradiction));
      return;
    }
    const aifc::EvidenceCitation* right = find_citation(classification, contradiction.right_id);
    if (right == nullptr) {
      seeded.check(false, step, "the right side of " + describe(contradiction) +
                                    " is not cited at all: " + describe(classification));
      return;
    }
    if (!citation_is_authoritative_current(*right) || aifc::is_unknown(right->semantic)) {
      seeded.check(false, step,
                   "the right side of " + describe(contradiction) +
                       " is not a CURRENT authoritative record with a declared class: " +
                       describe(*right));
      return;
    }
    if (right->semantic != contradiction.right_class || right->source != contradiction.right_source) {
      seeded.check(false, step, "the right side of " + describe(contradiction) +
                                    " does not match the cited record " + describe(*right));
      return;
    }
  }

  // (3) The penalty is exactly the configured value when the list is non-empty, and never
  // applied when it is empty.  The penalised confidence is never above the unpenalised one.
  const aifc::EvidenceCitation* winner_citation =
      winner == nullptr ? nullptr : find_citation(classification, winner->id);
  const std::uint32_t unpenalised =
      winner_citation == nullptr
          ? 0U
          : aifc::Confidence::weaker(winner_citation->confidence,
                                     aifc::source_confidence(winner_citation->source))
                .basis_points();
  if (!classification.contradictions.empty()) {
    seeded.check(classification.applied_penalty_basis_points == policy.contradiction_penalty, step,
                 "the applied penalty " +
                     std::to_string(classification.applied_penalty_basis_points) +
                     " is not the configured contradiction_penalty " +
                     std::to_string(policy.contradiction_penalty) + ": " + describe(classification));
    seeded.check(classification.state == aifc::ClassificationState::CONTRADICTED, step,
                 "a non-empty contradiction list was not reported as CONTRADICTED: " +
                     describe(classification));
    const std::uint32_t expected =
        unpenalised > policy.contradiction_penalty ? unpenalised - policy.contradiction_penalty : 0U;
    seeded.check(classification.confidence.basis_points() == expected, step,
                 "the penalised confidence " +
                     std::to_string(classification.confidence.basis_points()) +
                     " is not the unpenalised confidence " + std::to_string(unpenalised) +
                     " reduced by the configured penalty " +
                     std::to_string(policy.contradiction_penalty) + " (expected " +
                     std::to_string(expected) + "): " + describe(classification));
  } else {
    seeded.check(classification.applied_penalty_basis_points == 0U, step,
                 "an empty contradiction list still reported a penalty: " +
                     describe(classification));
    seeded.check(classification.confidence.basis_points() <= unpenalised, step,
                 "the confidence " + std::to_string(classification.confidence.basis_points()) +
                     " is above the unpenalised confidence " + std::to_string(unpenalised) + ": " +
                     describe(classification));
  }
  seeded.check(classification.confidence.basis_points() <= unpenalised, step,
               "the reported confidence " +
                   std::to_string(classification.confidence.basis_points()) +
                   " is above the unpenalised confidence " + std::to_string(unpenalised) + ": " +
                   describe(classification));
  if (failure_count() != before) return;

  // (4) A heuristic disagreement is never a contradiction, and a heuristic record is never
  // one side of one.
  for (const aifc::EvidenceCitation& citation : classification.citations) {
    if (citation.state != aifc::EvidenceState::EVIDENCE_CURRENT) continue;
    if (!aifc::source_is_heuristic(citation.source)) continue;
    if (citation.disposition != aifc::EvidenceDisposition::SUBORDINATE) {
      seeded.check(false, step, "a current heuristic record was not recorded as SUBORDINATE: " +
                                    describe(citation) + " in " + describe(classification));
      return;
    }
    if (winner == nullptr || citation.semantic == winner->semantic) continue;
    for (const aifc::ClassificationContradiction& contradiction : classification.contradictions) {
      if (contradiction.left_id == citation.id || contradiction.right_id == citation.id) {
        seeded.check(false, step,
                     "a heuristic disagreement appeared as a contradiction: " +
                         describe(contradiction) + " heuristic citation " + describe(citation));
        return;
      }
    }
  }

  // (5) Nothing is resolved silently: the reported class is one of the classes the current
  // authoritative records declare, or UNKNOWN -- never a synthesis, never a class that no
  // record declared.
  if (!aifc::is_unknown(classification.semantic)) {
    bool declared = false;
    for (const aifc::EvidenceCitation* citation : authoritative) {
      if (citation->semantic == classification.semantic) declared = true;
    }
    if (!declared) {
      seeded.check(false, step,
                   "the reported class " + std::string(aifc::to_string(classification.semantic)) +
                       " is not declared by any CURRENT authoritative record: " +
                       describe(classification));
      return;
    }
  }

  // (6) The corroboration count is exactly the number of other current authoritative
  // records that agree with the winner.
  if (winner != nullptr) {
    std::uint32_t corroborating = 0;
    for (const aifc::EvidenceCitation* citation : authoritative) {
      if (citation->id != winner->id && citation->semantic == winner->semantic) ++corroborating;
    }
    seeded.check(classification.corroboration_count == corroborating, step,
                 "corroboration_count " + std::to_string(classification.corroboration_count) +
                     " does not equal the " + std::to_string(corroborating) +
                     " other current authoritative records that agree with the winner: " +
                     describe(classification));
    if (failure_count() != before) return;
  }

  // (7) The list is stable under a permutation of the input order, and so is the decision.
  aifc::DecisionInput permuted = set.input;
  shuffle(permuted.evidence, seeded.rng());
  const aifc::Classification shuffled = engine.decide(permuted);
  if (!same_contradictions(classification.contradictions, shuffled.contradictions)) {
    seeded.check(false, step,
                 "the contradiction list changed when the same evidence set was supplied in "
                 "another order: original=" + describe_list(classification.contradictions) +
                     " permuted=" + describe_list(shuffled.contradictions));
    return;
  }
  if (classification.digest != shuffled.digest) {
    seeded.check(false, step,
                 "the decision digest changed when the same evidence set was supplied in another "
                 "order: original={" + describe(classification) + "} permuted={" +
                     describe(shuffled) + "}");
  }
}

// ---------------------------------------------------------------------------
// Cases
// ---------------------------------------------------------------------------

// SYNTHETIC evidence, REAL engine.  The full property, over randomly generated sets that
// mix agreeing records, disagreeing records, every non-heuristic source rank, heuristic
// records and non-current decoys.
AIFC_TEST("contradiction.randomized.iff_current_authoritative_disagreement") {
  SeededCase seeded("contradiction.randomized.iff_current_authoritative_disagreement");
  constexpr std::uint32_t kSteps = 600;
  for (std::uint32_t step = 0; step < kSteps; ++step) {
    const std::size_t before = failure_count();
    contradiction_step(seeded, step);
    if (failure_count() != before) break;
  }
}

// SYNTHETIC evidence, REAL engine.  Two current authenticated declarations that disagree:
// the winner is the precedence maximum, the loser is listed, and the configured penalty is
// applied exactly once and reported.
AIFC_TEST("contradiction.two_current_declarations_are_reported_with_the_penalty") {
  aifc::FlowRecord flow;
  flow.key = aifc_test::synthetic_flow_key(3);
  flow.id = aifc::derive_flow_id(flow.key);
  flow.generation = aifc::FlowGeneration{1};
  const aifc::AuthorityContext authority = make_authority();

  aifc::Rng rng(aifc::seed_from_text("contradiction.two_current_declarations"));
  aifc::EvidenceRecord first;
  first.id = aifc::make_evidence_id("ev-0001");
  first.publisher = aifc_test::synthetic_publisher(0);
  first.publisher_boot = aifc::PublisherBootId{1};
  first.session = aifc_test::synthetic_session(0);
  first.accepted_epoch = authority.epoch;
  first.accepted_boot = authority.coordinator_boot;
  first.flow_id = flow.id;
  first.flow_generation = flow.generation;
  first.generation = aifc::EvidenceGeneration{1};
  first.accepted_seq = rng.next_below(4U) + 1U;
  first.workload_generation = aifc::WorkloadGeneration{1};
  first.semantic = aifc::SemanticClass::COLLECTIVE;
  first.source = aifc::EvidenceSource::DECLARED_AUTHENTICATED;
  first.state = aifc::EvidenceState::EVIDENCE_CURRENT;
  first.confidence = aifc::source_confidence(first.source);
  first.content_digest = aifc::compute_evidence_digest(first);

  aifc::EvidenceRecord second = first;
  second.id = aifc::make_evidence_id("ev-0002");
  second.publisher = aifc_test::synthetic_publisher(1);
  second.session = aifc_test::synthetic_session(1);
  second.accepted_seq = 1000U;
  second.semantic = aifc::SemanticClass::INFERENCE_REQUEST;
  second.content_digest = aifc::compute_evidence_digest(second);

  aifc::ClassifierPolicy policy = aifc::ClassifierPolicy::initial();
  policy.contradiction_penalty = 2500U;

  aifc::DecisionInput input;
  input.flow = flow;
  input.policy = policy;
  input.authority = authority;
  input.evidence.push_back(first);
  input.evidence.push_back(second);

  aifc::DecisionEngine engine;
  const aifc::Classification classification = engine.decide(input);

  AIFC_CHECK_MSG(classification.semantic == aifc::SemanticClass::INFERENCE_REQUEST,
                 "the later acceptance sequence should win: " << describe(classification));
  AIFC_CHECK_MSG(classification.state == aifc::ClassificationState::CONTRADICTED,
                 "expected CONTRADICTED: " << describe(classification));
  AIFC_CHECK_EQ(classification.contradictions.size(), static_cast<std::size_t>(1));
  if (classification.contradictions.size() == 1U) {
    const aifc::ClassificationContradiction& contradiction = classification.contradictions[0];
    AIFC_CHECK_MSG(contradiction.left_id == second.id && contradiction.left_class == second.semantic,
                   "the left side should be the winner: " << describe(contradiction));
    AIFC_CHECK_MSG(contradiction.right_id == first.id &&
                       contradiction.right_class == first.semantic,
                   "the right side should be the losing declaration: " << describe(contradiction));
  }
  AIFC_CHECK_EQ(classification.applied_penalty_basis_points, 2500U);
  AIFC_CHECK_EQ(classification.confidence.basis_points(),
                aifc::source_confidence(aifc::EvidenceSource::DECLARED_AUTHENTICATED)
                        .basis_points() -
                    2500U);
}

// SYNTHETIC evidence, REAL engine.  A current heuristic record that declares a third class
// is never a contradiction, never corroboration and never the winner.
AIFC_TEST("contradiction.heuristic_disagreement_is_subordinate_not_a_contradiction") {
  aifc::FlowRecord flow;
  flow.key = aifc_test::synthetic_flow_key(4);
  flow.id = aifc::derive_flow_id(flow.key);
  flow.generation = aifc::FlowGeneration{1};
  const aifc::AuthorityContext authority = make_authority();

  aifc::EvidenceRecord declared;
  declared.id = aifc::make_evidence_id("ev-0100");
  declared.publisher = aifc_test::synthetic_publisher(0);
  declared.publisher_boot = aifc::PublisherBootId{1};
  declared.accepted_epoch = authority.epoch;
  declared.flow_id = flow.id;
  declared.flow_generation = flow.generation;
  declared.generation = aifc::EvidenceGeneration{1};
  declared.accepted_seq = 1;
  declared.semantic = aifc::SemanticClass::COLLECTIVE;
  declared.source = aifc::EvidenceSource::DECLARED_AUTHENTICATED;
  declared.state = aifc::EvidenceState::EVIDENCE_CURRENT;
  declared.confidence = aifc::source_confidence(declared.source);
  declared.content_digest = aifc::compute_evidence_digest(declared);

  aifc::EvidenceRecord heuristic = declared;
  heuristic.id = aifc::make_evidence_id("ev-0001");
  heuristic.publisher = aifc_test::synthetic_publisher(1);
  heuristic.session = aifc_test::synthetic_session(1);
  heuristic.accepted_seq = 1000000U;
  heuristic.generation = aifc::EvidenceGeneration{999};
  heuristic.workload_generation = aifc::WorkloadGeneration{999};
  heuristic.semantic = aifc::SemanticClass::SHUFFLE;
  heuristic.source = aifc::EvidenceSource::HEURISTIC;
  heuristic.confidence = aifc::source_confidence(heuristic.source);
  heuristic.content_digest = aifc::compute_evidence_digest(heuristic);

  aifc::ClassifierPolicy policy = aifc::ClassifierPolicy::initial();
  policy.allow_heuristic_evidence = true;

  aifc::DecisionInput input;
  input.flow = flow;
  input.policy = policy;
  input.authority = authority;
  input.evidence.push_back(heuristic);
  input.evidence.push_back(declared);

  aifc::DecisionEngine engine;
  const aifc::Classification classification = engine.decide(input);

  AIFC_CHECK_MSG(classification.semantic == aifc::SemanticClass::COLLECTIVE,
                 "the declaration should win over a heuristic guess: " << describe(classification));
  AIFC_CHECK_MSG(classification.contradictions.empty(),
                 "a heuristic disagreement was reported as a contradiction: "
                     << describe_list(classification.contradictions));
  AIFC_CHECK_EQ(classification.applied_penalty_basis_points, 0U);
  AIFC_CHECK_MSG(classification.state == aifc::ClassificationState::CURRENT,
                 "a single winning declaration should report CURRENT: " << describe(classification));

  bool subordinate = false;
  for (const aifc::EvidenceCitation& citation : classification.citations) {
    if (citation.id == heuristic.id) {
      subordinate = citation.disposition == aifc::EvidenceDisposition::SUBORDINATE;
    }
  }
  AIFC_CHECK_MSG(subordinate, "the heuristic record should be SUBORDINATE: "
                                  << describe(classification));
}

// SYNTHETIC evidence, REAL engine.  A stale record that declares a third class is not a
// contradiction either: losing currentness removes the ability to contradict.
AIFC_TEST("contradiction.stale_disagreement_is_not_a_contradiction") {
  aifc::FlowRecord flow;
  flow.key = aifc_test::synthetic_flow_key(5);
  flow.id = aifc::derive_flow_id(flow.key);
  flow.generation = aifc::FlowGeneration{1};
  const aifc::AuthorityContext authority = make_authority();

  aifc::EvidenceRecord live;
  live.id = aifc::make_evidence_id("ev-0200");
  live.publisher = aifc_test::synthetic_publisher(0);
  live.publisher_boot = aifc::PublisherBootId{1};
  live.accepted_epoch = authority.epoch;
  live.flow_id = flow.id;
  live.flow_generation = flow.generation;
  live.generation = aifc::EvidenceGeneration{1};
  live.accepted_seq = 5;
  live.semantic = aifc::SemanticClass::COLLECTIVE;
  live.source = aifc::EvidenceSource::DECLARED_AUTHENTICATED;
  live.state = aifc::EvidenceState::EVIDENCE_CURRENT;
  live.confidence = aifc::source_confidence(live.source);
  live.content_digest = aifc::compute_evidence_digest(live);

  aifc::ClassifierPolicy policy = aifc::ClassifierPolicy::initial();

  for (const aifc::EvidenceState state :
       {aifc::EvidenceState::EVIDENCE_STALE, aifc::EvidenceState::EVIDENCE_SUPERSEDED,
        aifc::EvidenceState::EVIDENCE_REVOKED, aifc::EvidenceState::EVIDENCE_INSUFFICIENT}) {
    aifc::EvidenceRecord dead = live;
    dead.id = aifc::make_evidence_id("ev-0201");
    dead.publisher = aifc_test::synthetic_publisher(1);
    dead.session = aifc_test::synthetic_session(1);
    dead.semantic = aifc::SemanticClass::STORAGE_DATA;
    dead.state = state;
    dead.content_digest = aifc::compute_evidence_digest(dead);

    aifc::DecisionInput input;
    input.flow = flow;
    input.policy = policy;
    input.authority = authority;
    input.evidence.push_back(live);
    input.evidence.push_back(dead);

    aifc::DecisionEngine engine;
    const aifc::Classification classification = engine.decide(input);
    AIFC_CHECK_MSG(classification.contradictions.empty(),
                   "state=" << aifc::to_string(state)
                            << " a non-current record was reported as a contradiction: "
                            << describe_list(classification.contradictions));
    AIFC_CHECK_MSG(classification.semantic == aifc::SemanticClass::COLLECTIVE,
                   "state=" << aifc::to_string(state) << " expected the current declaration -- "
                            << describe(classification));
    AIFC_CHECK_EQ(classification.applied_penalty_basis_points, 0U);
  }
}

// SYNTHETIC evidence, REAL engine.  The documented boundary of the "iff": when the
// penalised confidence is below minimum_publishable_confidence the class is reported as
// UNKNOWN/INSUFFICIENT and the penalty is not applied, so the list is empty even though two
// current authoritative records disagree.  The disagreement itself must still be visible in
// the citations -- it is never hidden, only unpublishable.
AIFC_TEST("contradiction.below_threshold_suppresses_the_penalty_but_not_the_disagreement") {
  aifc::FlowRecord flow;
  flow.key = aifc_test::synthetic_flow_key(6);
  flow.id = aifc::derive_flow_id(flow.key);
  flow.generation = aifc::FlowGeneration{1};
  const aifc::AuthorityContext authority = make_authority();

  aifc::EvidenceRecord left;
  left.id = aifc::make_evidence_id("ev-0300");
  left.publisher = aifc_test::synthetic_publisher(0);
  left.publisher_boot = aifc::PublisherBootId{1};
  left.accepted_epoch = authority.epoch;
  left.flow_id = flow.id;
  left.flow_generation = flow.generation;
  left.generation = aifc::EvidenceGeneration{1};
  left.accepted_seq = 1;
  left.semantic = aifc::SemanticClass::COLLECTIVE;
  left.source = aifc::EvidenceSource::DECLARED_AUTHENTICATED;
  left.state = aifc::EvidenceState::EVIDENCE_CURRENT;
  left.confidence = aifc::source_confidence(left.source);
  left.content_digest = aifc::compute_evidence_digest(left);

  aifc::EvidenceRecord right = left;
  right.id = aifc::make_evidence_id("ev-0301");
  right.publisher = aifc_test::synthetic_publisher(1);
  right.accepted_seq = 2;
  right.semantic = aifc::SemanticClass::INFERENCE_REQUEST;
  right.content_digest = aifc::compute_evidence_digest(right);

  aifc::ClassifierPolicy policy = aifc::ClassifierPolicy::initial();
  policy.contradiction_penalty = 2000U;
  policy.minimum_publishable_confidence = 8000U;  // 9000 - 2000 == 7000 < 8000

  aifc::DecisionInput input;
  input.flow = flow;
  input.policy = policy;
  input.authority = authority;
  input.evidence.push_back(left);
  input.evidence.push_back(right);

  aifc::DecisionEngine engine;
  const aifc::Classification classification = engine.decide(input);
  AIFC_CHECK_MSG(aifc::is_unknown(classification.semantic),
                 "expected UNKNOWN under the raised threshold: " << describe(classification));
  AIFC_CHECK_MSG(classification.state == aifc::ClassificationState::INSUFFICIENT,
                 "expected INSUFFICIENT under the raised threshold: " << describe(classification));
  AIFC_CHECK_MSG(classification.contradictions.empty(),
                 "an unpublishable decision should report no applied contradiction: "
                     << describe_list(classification.contradictions));
  AIFC_CHECK_EQ(classification.applied_penalty_basis_points, 0U);

  // The engine's winner here is the record with the later acceptance sequence (right);
  // left is the disagreeing record that lost.
  bool losing_side_visible = false;
  bool winning_side_below_threshold = false;
  for (const aifc::EvidenceCitation& citation : classification.citations) {
    if (citation.id == left.id) {
      losing_side_visible = citation.disposition == aifc::EvidenceDisposition::CONTRADICTING;
    }
    if (citation.id == right.id) {
      winning_side_below_threshold =
          citation.disposition == aifc::EvidenceDisposition::BELOW_THRESHOLD;
    }
  }
  AIFC_CHECK_MSG(losing_side_visible,
                 "the disagreement was hidden: the losing record is not cited CONTRADICTING -- "
                     << describe(classification));
  AIFC_CHECK_MSG(winning_side_below_threshold,
                 "the winning record is not cited BELOW_THRESHOLD -- " << describe(classification));

  // The same evidence set under the default threshold reports the contradiction.
  policy.minimum_publishable_confidence = 1000U;
  input.policy = policy;
  const aifc::Classification published = engine.decide(input);
  AIFC_CHECK_MSG(published.state == aifc::ClassificationState::CONTRADICTED,
                 "expected CONTRADICTED at the default threshold: " << describe(published));
  AIFC_CHECK_EQ(published.contradictions.size(), static_cast<std::size_t>(1));
  AIFC_CHECK_EQ(published.applied_penalty_basis_points, 2000U);
}

// SYNTHETIC evidence, REAL engine.  The consideration cap shrinks the *display* of
// non-decisive citations; it never removes a contradiction or a decisive citation.  With a
// cap of 3 over 14 records, all 6 disagreements, all 3 corroborations and the selected
// record must still be reported, and only the 4 non-current citations may be excluded.
AIFC_TEST("contradiction.consideration_cap_never_hides_a_contradiction") {
  aifc::FlowRecord flow;
  flow.key = aifc_test::synthetic_flow_key(8);
  flow.id = aifc::derive_flow_id(flow.key);
  flow.generation = aifc::FlowGeneration{1};
  const aifc::AuthorityContext authority = make_authority();

  aifc::ClassifierPolicy policy = aifc::ClassifierPolicy::initial();
  policy.max_evidence_considered = 3U;
  policy.contradiction_penalty = 1000U;

  aifc::DecisionInput input;
  input.flow = flow;
  input.policy = policy;
  input.authority = authority;

  aifc::EvidenceRecord winner;
  winner.id = aifc::make_evidence_id("ev-0400");
  winner.publisher = aifc_test::synthetic_publisher(0);
  winner.publisher_boot = aifc::PublisherBootId{1};
  winner.accepted_epoch = authority.epoch;
  winner.flow_id = flow.id;
  winner.flow_generation = flow.generation;
  winner.generation = aifc::EvidenceGeneration{1};
  winner.accepted_seq = 100;
  winner.semantic = aifc::SemanticClass::COLLECTIVE;
  winner.source = aifc::EvidenceSource::DECLARED_AUTHENTICATED;
  winner.state = aifc::EvidenceState::EVIDENCE_CURRENT;
  winner.confidence = aifc::source_confidence(winner.source);
  winner.content_digest = aifc::compute_evidence_digest(winner);
  input.evidence.push_back(winner);

  std::vector<aifc::EvidenceId> expected;
  for (std::uint32_t index = 0; index < 6U; ++index) {
    aifc::EvidenceRecord record = winner;
    record.id = aifc::make_evidence_id("ev-04" + std::to_string(10U + index));
    record.publisher = aifc_test::synthetic_publisher(1U + (index % 4U));
    record.accepted_seq = 1U + index;
    record.semantic = aifc::SemanticClass::INFERENCE_REQUEST;
    record.source = aifc::EvidenceSource::TOPOLOGY_CORRELATED;
    record.confidence = aifc::source_confidence(record.source);
    record.content_digest = aifc::compute_evidence_digest(record);
    expected.push_back(record.id);
    input.evidence.push_back(record);
  }
  // Three further records that agree with the winner, so the cap has corroborating
  // citations to keep.
  for (std::uint32_t index = 0; index < 3U; ++index) {
    aifc::EvidenceRecord record = winner;
    record.id = aifc::make_evidence_id("ev-05" + std::to_string(10U + index));
    record.publisher = aifc_test::synthetic_publisher(2);
    record.accepted_seq = 200U + index;
    record.source = aifc::EvidenceSource::CONTRACT_DERIVED;
    record.confidence = aifc::source_confidence(record.source);
    record.content_digest = aifc::compute_evidence_digest(record);
    input.evidence.push_back(record);
  }
  // Four non-current records, which are the only citations the cap may drop.
  for (std::uint32_t index = 0; index < 4U; ++index) {
    aifc::EvidenceRecord record = winner;
    record.id = aifc::make_evidence_id("ev-06" + std::to_string(10U + index));
    record.publisher = aifc_test::synthetic_publisher(3);
    record.accepted_seq = 300U + index;
    record.semantic = aifc::SemanticClass::MODEL_STATE_TRANSFER;
    record.state = aifc::EvidenceState::EVIDENCE_STALE;
    record.content_digest = aifc::compute_evidence_digest(record);
    input.evidence.push_back(record);
  }

  aifc::DecisionEngine engine;
  const aifc::Classification classification = engine.decide(input);

  AIFC_CHECK_MSG(classification.semantic == aifc::SemanticClass::COLLECTIVE,
                 "the declaration should win: " << describe(classification));
  AIFC_CHECK_EQ(classification.contradictions.size(), expected.size());
  for (const aifc::EvidenceId& id : expected) {
    bool found = false;
    for (const aifc::ClassificationContradiction& contradiction : classification.contradictions) {
      if (contradiction.right_id == id) found = true;
    }
    AIFC_CHECK_MSG(found, "contradiction with " << id.value()
                                                << " was dropped by the consideration cap of "
                                                << policy.max_evidence_considered << ": "
                                                << describe_list(classification.contradictions));
  }
  std::size_t selected = 0;
  std::size_t contradicting = 0;
  std::size_t corroborating = 0;
  std::size_t excluded = 0;
  for (const aifc::EvidenceCitation& citation : classification.citations) {
    if (citation.disposition == aifc::EvidenceDisposition::SELECTED) ++selected;
    if (citation.disposition == aifc::EvidenceDisposition::CONTRADICTING) ++contradicting;
    if (citation.disposition == aifc::EvidenceDisposition::CORROBORATING) ++corroborating;
    if (citation.disposition == aifc::EvidenceDisposition::EXCLUDED_BY_LIMIT) ++excluded;
  }
  AIFC_CHECK_EQ(selected, static_cast<std::size_t>(1));
  AIFC_CHECK_EQ(contradicting, static_cast<std::size_t>(6));
  AIFC_CHECK_EQ(corroborating, static_cast<std::size_t>(3));
  AIFC_CHECK_EQ(excluded, static_cast<std::size_t>(4));
}

// SYNTHETIC evidence, REAL engine.  A sweep over every penalty value in the randomized
// range confirms the winning class is always one of the declared classes: a contradiction
// is reported, never resolved into a class that no record declared.
AIFC_TEST("contradiction.winning_class_is_always_declared_never_synthesised") {
  SeededCase seeded("contradiction.winning_class_is_always_declared_never_synthesised");
  const std::uint64_t penalties[4] = {0U, 500U, 2000U, 4000U};
  for (const std::uint64_t penalty : penalties) {
    for (std::uint32_t step = 0; step < 100U; ++step) {
      const std::size_t before = failure_count();
      aifc::ClassifierPolicy policy;
      const GeneratedSet set = generate_set(seeded, step, policy);
      aifc::DecisionInput input = set.input;
      input.policy.contradiction_penalty = static_cast<std::uint32_t>(penalty);

      aifc::DecisionEngine engine;
      const aifc::Classification classification = engine.decide(input);
      if (aifc::is_unknown(classification.semantic)) continue;

      bool declared = false;
      for (const aifc::EvidenceCitation& citation : classification.citations) {
        if (citation.state != aifc::EvidenceState::EVIDENCE_CURRENT) continue;
        if (aifc::source_is_heuristic(citation.source)) continue;
        if (citation.semantic == classification.semantic) declared = true;
      }
      const std::string detail = "penalty=" + std::to_string(penalty) + " set={" +
                                 describe(set.records.front()) + " ... " +
                                 std::to_string(set.records.size()) + " records} result={" +
                                 describe(classification) + "}";
      seeded.check(declared, step, "the winning class was not declared by any current "
                                   "authoritative record: " + detail);
      seeded.check(classification.confidence.basis_points() <=
                       aifc::source_confidence(aifc::EvidenceSource::DECLARED_AUTHENTICATED)
                           .basis_points(),
                   step, "the confidence exceeds what any single source can justify: " + detail);
      if (failure_count() != before) break;
    }
  }
}

}  // namespace
